<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE employees [
        <!ELEMENT employees (Employee+)>
        <!ELEMENT Employee (firstname,lastname,age,position,employer,address)>
        <!ATTLIST Employee id CDATA #REQUIRED>
        <!ELEMENT firstname (#PCDATA)>
        <!ELEMENT lastname (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT position (#PCDATA)>
        <!ELEMENT employer (name,startDate,endDate)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT startDate (#PCDATA)>
        <!ELEMENT endDate (#PCDATA)>
        <!ELEMENT address (street,streetNo,section,city)>
        <!ELEMENT street (#PCDATA)>
        <!ELEMENT streetNo (#PCDATA)>
        <!ELEMENT section (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        ]>
<employees>
    <Employee id="1">
        <firstname>Ivan</firstname>
        <lastname>Ivanov</lastname>
        <age>25</age>
        <position>programmer</position>
        <employer>
            <name>Dimityr Dimitrov</name>
            <startDate>27.08.1998</startDate>
            <endDate>16.01.2002</endDate>
        </employer>
        <address>
            <street>Georgi Izmirliev</street>
            <streetNo>17</streetNo>
            <section>Veliko Tarnovo</section>
            <city>Veliko Tarnovo</city>
        </address>
    </Employee>
    <Employee id="2">
        <firstname>Georgi</firstname>
        <lastname>Georgiev</lastname>
        <age>35</age>
        <position>doctor</position>
        <employer>
            <name>Stefan Georgiev</name>
            <startDate>15.11.2003</startDate>
            <endDate>10.03.2007</endDate>
        </employer>
        <address>
            <street>Nikola Gabrovski</street>
            <streetNo>41</streetNo>
            <section>Veliko Tarnovo</section>
            <city>Veliko Tarnovo</city>
        </address>
    </Employee>
    <Employee id="3">
        <firstname>Mihail</firstname>
        <lastname>Mihov</lastname>
        <age>28</age>
        <position>police officer</position>
        <employer>
            <name>Rumyana Bachvarova</name>
            <startDate>01.01.2015</startDate>
            <endDate>01.01.2016</endDate>
        </employer>
        <address>
            <street>Bacho Kiro</street>
            <streetNo>7</streetNo>
            <section>Veliko Tarnovo</section>
            <city>Veliko Tarnovo</city>
        </address>
    </Employee>
</employees>